### ISSUE TITLE
Add juju push-resource to commands.md

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1160]
juju push-resource

    usage: juju push-resource [options] service name=file
    purpose: upload a file as a resource for a service
    
    options:
    -m, --model (= "")
        juju model to operate in
    
    This command uploads a file from your local disk to the juju
    controller to be used as a resource for a service.

**Comment by evilnick** [comment]
there is no need to add anything to commands.md It is a generated file. Any
command that is exposed through juju help is automatically included
whenever the generation tools are re-run.

sadly the help is in an inconsistent, messy state so a lot of this needs
manual editing afterwards, which is why it is out of date. I will re-run
the tool though, as there are significant changes since we last regenerated.

On 9 June 2016 at 16:09, Matthew Helmke <notifications@github.com> wrote:

> juju push-resource
>
> usage: juju push-resource [options] service name=file
> purpose: upload a file as a resource for a service
>
> options:
> -m, --model (= "")
>     juju model to operate in
>
> This command uploads a file from your local disk to the juju
> controller to be used as a resource for a service.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/juju/docs/issues/1160>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAHCWlAPLWGc7GUzgi_GfA17SUUTjS7tks5qKCyfgaJpZM4IyFC9>
> .
>



-- 
Nick Veitch,
CDO Documentation
Canonical

**Comment by evilnick** [comment]
I am going to close this because, as noted, it is an issue that solves itself
