### ISSUE TITLE
Controllers and models can be confusing; ideas to consider for the next round of edits

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1172]
This is a bigger issue that we should think about in the long term, after the 2.0 updates are complete.
1. A controller is a model that has the specific purpose of being in control of other models. Models are subservient to a controller, but a controller is a subset of the type "model". Even my explanation here forces itself to be read more than once. I wonder if we can find a way to make the relationship clearer.
2. Because of this relationship, interacting with controllers and models sometimes use different commands, like `list-controllers` and `list-models`, but sometimes the same command can be used on either, such as `juju switch`. We should find a way to better explain why.

To list the controllers that you have created, use:

```
juju list-controllers

  CONTROLLER    MODEL         USER         CLOUD/REGION
  mycontroller* controller    admin@local  joyent/us-east-3
  test          default       admin@local  AWS/eu-west-1
```

The current controller is indicated with an *.

To select the current controller and/or model, use:

```
juju switch mymodel        (switch to mymodel on current controller)
juju switch mycontroller   (switch current controller to mycontroller)
juju switch mycontroller:mymodel   (switch to mymodel on mycontroller)
```

**Comment by pmatulis** [comment]
The change in terminology (controller model) does indeed make documention a more challenging task. 
A way around this would be to no longer refer to a controller as a machine but this is not possible due to commands such as `list-controllers` and `destroy-controller` and so on. To try to no longer distinguish between machine or model doesn't work either since, for example, you can `switch` to a model on the controller (machine) that is not the controller model.

One option is to no longer use the term 'controller' without a qualifier (i.e. "controller model" and "controller machine"). A second idea would be to state outright in some introductory text that "controller" is the machine and "controller model" is the model.

As regards to `juju switch`, I like to think of this command as expressly changing to a model (or stating the current model) and I said this [here](https://jujucharms.com/docs/devel/models). If invoked by specifying just a controller (machine; sigh) then the model you get is the last used model.

Still, if one wants to switch to the controller model you could very easily end up with stuff like this:

`juju switch controller`
`juju switch maas-controller:controller`
`juju switch controller:controller`

We will need to be careful with how we document the above.

**Comment by pmatulis** [comment]
I believe this issue to be clarified by the recent PRs of #2368 and #2368. Closing.
