### ISSUE TITLE
getting-started updates for 2.0 for non-Xenial OS'es

### ISSUE THREAD

**Issue by arosales** [juju/docs#1189]
In addition to ensuring we stay aligned with https://jujucharms.com/get-started  we need to update the 2.0 install for:
- OSX (brew and/or direct download from https://launchpad.net/juju-core/+milestone/2.0-beta9)
- Windows
- Vagrant Xenial Juju box

The Xenial case looks to be covered pretty well at:
https://jujucharms.com/docs/devel/getting-started

however, that page links to other non-Ubuntu OSes:
https://jujucharms.com/docs/devel/getting-started-general

which then if your a non-Ubuntu users one lands on:
https://jujucharms.com/docs/devel/reference-releases

https://jujucharms.com/docs/devel/reference-releases
- needs updating for 2.0 as well as adding Vagrant instructions.

Note https://jujucharms.com/docs/stable/getting-started#mac-osx also suggests Vagrant:
https://jujucharms.com/docs/stable/config-vagrant
- Needs latest Xenial Juju Box which there are none of that I could find thus I filed https://bugs.launchpad.net/cloud-images/+bug/1593470

**Comment by evilnick** [comment]
Thanks for reporting this!

As I understand it,  https://jujucharms.com/get-started is going away.

https://jujucharms.com/docs/devel/reference-releases is up to date - the correct versions of Juju are shown under stable and proposed etc. This gets updated every time there is a release, so when 2.0 is the stable release it will be listed under the stable releases. Though i think because of changes in pakaging we should start talking about 14.04 and 16.04 versions (ie. apt install juju will fetch different things). Is there something else which should change here?

The Vagrant case is an interesting one though. I asked for clarification on this about a month ago!

**Comment by evilnick** [comment]
I think, barring Vagrant, all these various use cases have been covered by changes in the last month to the install page and the new getting started
