### ISSUE TITLE
First result when searching devel docs for "google" is a 404

### ISSUE THREAD

**Issue by mjs** [juju/docs#1218]
To reproduce:
- visit http://jujucharms.com/docs/
- Select the "devel" docs
- Enter "google" into the search box
- The first hit is for https://jujucharms.com/docs/master/config-gce ("Configuring for the Google Compute Engine"). This is a 404.

This isn't an awesome experience.

**Comment by evilnick** [comment]
Yup, I agree. Search isn't part of docs though, the issue is with the Jujucharms site:
see also:

https://github.com/CanonicalLtd/jujucharms.com/issues/286
https://github.com/CanonicalLtd/jujucharms.com/issues/288
https://github.com/CanonicalLtd/jujucharms.com/issues/304

I believe search is also broken for charms and charm text too

**Comment by urosj** [comment]
No sure this is valid. 

https://jujucharms.com/docs/search/?text=google&version=2.1

If you, however, search in charm store, yes, there are no charms named google ...
