### ISSUE TITLE
Constraints Pages Updates

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#1369]
Just a list of notes on further cleanups on the constraints page:
- It’s cpu-cores, not core(s). We should update the doc to be consistent.
- ECU is no longer valid; they use vCPU now. Can this be updated? Can we talk about what it might mean for other providers?
- Is it possible to use the container constraint in a substrate besides GCE?
- Arch in Manual Provider is misspelled: “arhc”
- https://jujucharms.com/docs/2.0/reference-constraints isn’t the same as https://jujucharms.com/docs/devel/reference-constraints. The former seems to be out of date? Why are they different?

@anastasiamac adding you to confirm and help with the questions.

**Comment by evilnick** [comment]
1 - see https://bugs.launchpad.net/juju/+bug/1620056

2 - do you mean ecu is no longer valid in the docs or the code?

3 - I guess that is for @anastasiamac 

4-thanks!

5 - for the same reason the version of juju you currently get from the  archive is different to the one you get from the PPA.

**Comment by anastasiamac** [comment]
@evilnick, @nskaggs for 3, this is a question for @dimitern or @frobware:
Is it possible to use the container constraint in a substrate besides GCE?

**Comment by nskaggs** [comment]
2) I'm saying I'm not sure what the code looks like nowadays, but Amazon doesn't use ECU anymore, but vCPU. At the least the docs should refer to vCPU and not ECU.

**Comment by evilnick** [comment]
ok, thanks we'll fix that up

**Comment by pmatulis** [comment]
It looks like the only pending item here is:

*Is it possible to use the container constraint in a substrate besides GCE?*

**Comment by jameinel** [comment]
So, 'container' on GCE appears to actually mean "what GCE virtualization should we use for the machines that we start". However, the only string you can actually pass on GCE is "kvm".
Since you can't actually specify a different vtype:
https://github.com/juju/juju/blob/develop/provider/gce/instancetypes.go
https://github.com/juju/juju/blob/develop/provider/gce/environ_policy.go

I haven't found Google docs that mention a different value that could be passed other than "kvm".

I feel like having "container" exposed is actually confusing the issue, because it muddies the water between running applications inside real containers, and virtualization types.

I'd rather we deprecate the option entirely and drop it from the documentation.

**Comment by pmatulis** [comment]
@jameinel Thank you. I agree it is more confusing that useful. I'll remove it.
