### ISSUE TITLE
/getting-started: Update example charms that have version and status enabled

### ISSUE THREAD

**Issue by arosales** [juju/docs#1382]
On the intro example page update the example charms to have version and status set, or possibly select a different bundle that has those features.  

As a new user tires Juju these fields being set and view in status helps improve the first user experience as we try to show case Juju in a "easy/familiar" example.

**Comment by evilnick** [comment]
I would think it is better to update the charms (which will surely be beneficial at some point anyhow).

The examples are usually chosen, particularly getting started, to be complex enough to show some of the features of Juju (bundles, relations, exposing etc) but simple enough to work quickly and without using too many resources. If there is another charm/bundle which does include these features which we should be using and also satisfies our desire to keep things simple, we are open to suggestions!

**Comment by pmatulis** [comment]
The main Getting Started page has since morphed into JAAS so this lessens the complaint. [The Getting started with Juju and LXD](https://jujucharms.com/docs/stable/tut-lxd) page uses the 'mysql' charm which  indeed does not include a `Version` and gives a `Status` of 'unknown'. I honestly don't think this is worth pursuing. Closing.
