### ISSUE TITLE
all status output examples need to be updated

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1456]
to reflect recent changes in the output

**Comment by bac** [comment]
Yes, some fundamental commands like bootstrap have changed parameter order.

**Comment by matthewhelmke** [comment]
That is more of an input issue and has already been updated in #1440. This issue is about capturing the output of commands and updating the places in the documentation where we show output. That involves checking each instance, comparing the new and old output, and updating those which do not match.

**Comment by bac** [comment]
Sorry, I thought this bug referenced the generated file served at:

https://jujucharms.com/docs/2.0/commands

That page is incorrect.

**Comment by matthewhelmke** [comment]
Ahh, I see. Thanks. We will look into that. :)

**Comment by evilnick** [comment]
that was fixed in #1473

**Comment by bac** [comment]
Thanks @evilnick
