### ISSUE TITLE
Broken links/missing docs in How To section of navigation

### ISSUE THREAD

**Issue by degville** [juju/docs#1534]
These may have been intended to stay in devel, but they're now in 2.0.

Deploy a Node.js app
Test and deploy on Rails
Deploy Drupal Windows charm

**Comment by evilnick** [comment]
Ah, yes - I cut them from release because they are out of date and nobody responded to how they should work with 2.0. They snuck back in when we had that snafu with master and 2.0 diverging because people merged against the wrong branch. Easiest to remove them totally i think and update when we have the info
