### ISSUE TITLE
Juju controller recommended production requirements

### ISSUE THREAD

**Issue by szeestraten** [juju/docs#1589]
There should be some documentation for recommended production requirements for Juju controllers with regards to hardware specifications such as CPU, memory and last but not least, disk sizes (see also https://bugs.launchpad.net/juju/+bug/1631138).

Some guidelines or at least minimum requirements would be a good start.

**Comment by pmatulis** [comment]
@szeestraten This was started with #2049 where memory and CPU was added. It seems that disk space should only be a concern with a LXD-based controller. What do you propose? I have been using such a controller for a long while and I see:

```
/dev/vda1       9.7G  5.2G  4.5G  54% /

**Comment by szeestraten** [comment]
I'd like to see some storage requirements or rough numbers on how to size controllers and what disk usage to expect.

We (and I guess others as well) are running controllers on MAAS controllers so it would be nice to know how to spec these properly.

**Comment by pmatulis** [comment]
I still think we just need to focus on LXD (images and containers). For MAAS, you just need to add what **its** [recommended specs](https://docs.ubuntu.com/maas/2.1/en/#minimum-requirements) are.

**Comment by szeestraten** [comment]
Ok, but I created the issue for production deployments which for MAAS means it is not running in LXD containers. Also, the MAAS recommended specs are for MAAS, not Juju as we've had enough Juju controllers crash due to either high memory usage (and leaks for that matter) or MongoDB/logs running a bit wild with large models such as OpenStack HA deployments.

**Comment by pmatulis** [comment]
I'll add a note for space considerations if the controller will be for the localhost cloud (LXD).

**Comment by szeestraten** [comment]
Again, the issue is about production deployments on MAAS and etc. The localhost cloud (LXD) should not be involved at all as it is not a production cloud.

**Comment by pmatulis** [comment]
IIUC, you want to know what specs to use for a MAAS node that will host a Juju controller. This depends on the proportion of the **number** of workload MAAS nodes there are and the **volatile nature** of the work being done. That is, are there just a few nodes that are being recommissioned/deployed within a short time frame or is there a large number of nodes undergoing this activity? There are probably other factors too. So it's hard to put this kind of stuff into writing and associate numbers to them. I fear they'll end up being quite meaningless, even if we include multiple scenarios, since there is much subjectivity involved.

I am going to merge #2144 today and, in so doing, close out this present issue. If, however, you find my explanation (for not including such numbers) lacking then let me know and I'll open a separate issue that specifically targets your use case. Please add details here if I did not understand it adequately.
