### ISSUE TITLE
Charm tool missing installation guide for <16.04

### ISSUE THREAD

**Issue by hatched** [juju/docs#1649]
https://jujucharms.com/docs/stable/tools-charm-tools

**Comment by matthewhelmke** [comment]
I see that @cmars removed the PPA/deb instructions and added " 16.04 LTS (Xenial) and later releases" last November in [this commit](https://github.com/juju/docs/commit/d490898af9a3038e3d1a7cfacebd16f54553403e) with the comment `charm-tools deb packages are no longer supported.`

I also see that both [Launchpad](https://launchpad.net/charm-tools) and [GitHub](https://github.com/juju/charm-tools) show the PPA instructions.

I'm torn about what to do here as I really think we must have install instructions for Trusty users at a minimum, since that is still supported, but I've no clue what to write for them.

Anyone from the charm tools group able to help us out here? @marcoceppi ? @nskaggs ? @cmars ? @chuckbutler ?

**Comment by cmars** [comment]
AIUI only the charm snap is actively being supported, debs are deprecated, and snaps can now be installed on trusty. @marcoceppi ?

**Comment by chuckbutler** [comment]
xref with https://github.com/juju/charm-tools/issues/303  which is a similar thread

**Comment by matthewhelmke** [comment]
I see the thread that @chuckbutler mentioned has been closed, but I still don't have a definitive answer for what to tell users on trusty.

Also, should we file bugs on both [Launchpad](https://launchpad.net/charm-tools) and [GitHub](https://github.com/juju/charm-tools) as they still show the PPA instructions so that users who find those will not be frustrated by the PPAs??

**Comment by hatched** [comment]
The issue with the PPA is that it doesn't include the plugins, like terms for example.

**Comment by matthewhelmke** [comment]
Okay, so it sounds like we should file bugs on both Launchpad and GitHub as they still show the PPA instructions and are telling users to install from them.

When we have install instructions available for trusty users, please ping us and we will change the page.

**Comment by pmatulis** [comment]
The Juju docs portion was fixed via #2092 and I updated https://github.com/juju/charm-tools/issues/306 to explain that the only outstanding issue is to update the Launchpad Tools page to no longer mention the PPA. Closing this issue.
