### ISSUE TITLE
New loop device default value

### ISSUE THREAD

**Issue by frankban** [juju/docs#1822]
From https://github.com/CanonicalLtd/jujucharms.com/issues/455

On the docs, Getting started with Juju section, the recomendation is let all default and option bellow:
Size in GB of the new loop device (1GB minimum) [default=10GB]: 20.
however, when i installed here, the default value is now 100 GB:
its like:
Size in GB of the new loop device (1GB minimum) [default=100GB]?:

**Comment by evilnick** [comment]
The default value now depends on the amount of storage available (i.e. it is variable)

Since this does not effect the outcome of installation (we specify the value to use) and since adding a note to explain that the default value which we don't use is variable will just add to clutter in the instructions, we do not intend to change this.
