### ISSUE TITLE
Bindings documentation is inaccurate

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1931]
From https://bugs.launchpad.net/juju/+bug/1698269:

The web documentation for 2.2 describes binding multiple endpoints using this commandline:

juju deploy --bind "db:db-space db-admin:admin-space default-space" mysql

In reality, the commandline juju will accept is:

juju deploy --bind "default-space db=db-space db-admin=admin-space" mysql

**Comment by evilnick** [comment]
is this a change in 2.2? I can't imagine this has always been wrong

**Comment by jameinel** [comment]
at one point we were looking at : but I think it has been = for all of
2.0.0 final

John
=:->

On Jun 16, 2017 20:26, "Nick Veitch" <notifications@github.com> wrote:

is this a change in 2.2? I can't imagine this has always been wrong

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/juju/docs/issues/1931#issuecomment-309071583>, or mute
the thread

**Comment by evilnick** [comment]
OK, because we only changed to that notation in reference to another issue after 2.1 came out.
@degville do you know where that example came from?

**Comment by degville** [comment]
@evilnick I think it came from the 2.1 release notes, and specifically, from a separate networking document (Networking changes) we used to compile those notes before they were sent.

**Comment by evilnick** [comment]
Yes, that seems to be the case. :(
