### ISSUE TITLE
Charm Tools updates

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#2092]
Charm tools should be installed as a strict snap now, and it should work everywhere. Let's clean up / update the instructions on https://jujucharms.com/docs/stable/tools-charm-tools and https://jujucharms.com/docs/stable/charms-deploying#addendum:-local-charms, Other references should just point to https://jujucharms.com/docs/stable/tools-charm-tools.

**Comment by nskaggs** [comment]
@marcoceppi is there a charm tools help / online doc for installation we could or should point to instead of our own https://jujucharms.com/docs/stable/tools-charm-tools?

**Comment by pmatulis** [comment]
@nskaggs IIUC, you are requesting that

https://jujucharms.com/docs/1.25/tools-charm-tools

be updated to refer to snaps as opposed to a PPA? And since /usr/bin/snap is not installed OOB with Trusty do you think we need to include an APT command to install it? See [here](http://paste.ubuntu.com/25521436/) for a couple of side issues.

OK re rationalising:

https://jujucharms.com/docs/2.0/charms-deploying
https://jujucharms.com/docs/2.1/charms-deploying
https://jujucharms.com/docs/2.2/charms-deploying

**Comment by nskaggs** [comment]
@pmatulis I would say yes, we want to point people at installing charm tools from a snap always, as that is the upstream recommendation. What's in the ppa is old, and isn't being updated. I would defer issues with that recommendation to upstream @marcoceppi @tvansteenburgh et la.

**Comment by pmatulis** [comment]
This is done. I've opened #2103 for the question of the tools on macos and windows.
