### ISSUE TITLE
src/en/authors-charm-leadership.md improperly formatted

### ISSUE THREAD

**Issue by jameinel** [juju/docs#2266]
The rendering looks correct in Github, but it does not in the official docs.
Specifically on this page:
https://jujucharms.com/docs/2.2/authors-charm-leadership
The python snippet here:
def set_shared_settings():
    if is_leader():

Is not properly indented. While it does look good here:
https://github.com/juju/docs/blob/master/src/en/authors-charm-leadership.md

It seems that whatever Markdown rendering we're doing on the live section doesn't auto-create preformated sections. I think it just means we need to wrap it in "```" sections.

**Comment by evilnick** [comment]
Yeah, there are probably a few badly formatted python examples because these pages weren't added by the docs team. Blocks of code should always be fenced with backticks otherwise unexpected things can happen.
Thanks for the pointer to this one, I will see if we can find any similar ones in the author docs.
