### ISSUE TITLE
new user management/permissions

### ISSUE THREAD

**Issue by evilnick** [juju/docs#250]

**Comment by petermatulis** [comment]
@evilnick 
Fished this [1] out of the 1.21.1 section of reference-release-notes.md. Is this what you're after?

I just realized that [reference-release-notes.html](https://jujucharms.com/docs/devel/reference-release-notes.html) does not render well. Is that a known issue? Example:

no-highlight $JUJU_HOME/environments/app-stack.jenv

[1]
=============
  ### Managing who can connect to the Juju environment

  Juju now supports multiple people connecting to the environment with
  their own identity and credentials.

  When an environment is bootstrapped the "admin" user is created (this
  will change with 1.22 to reflect the name of the logged in user).

  Even though there is support for multiple users, there is not yet support
  for fine grain permissions. These will come in time. The
  only permission checked at this stage is that only the "admin" user
  can create or disable other users. Any user is now able to change
  their own password.

  The user commands are grouped under the ```juju user``` command:

  ```bash
  juju user
  usage: juju user <command> ...
  purpose: manage user accounts and access control
  ```

      "juju user" is used to manage the user accounts and access control
      in the Juju environment.

      commands:
          add - adds a user
          change-password - changes the password of the current user
          disable - disable a user to stop the user logging in
          enable - reenables a disabled user to allow the user
                            to log in
          help - show help on a command or other topic
          info - shows information on a user
          list - shows all users

  You can add a user like this:

  ```bash
  juju user add test "Test User"
  ```

  To generate a random strong password, use the --generate option.

  ```bash
  password:
  type password again:
  user "Test User (test)" added
  environment file written to /home/tim/some-dir/test.jenv
  ```

  The generated environment file still needs to be copied into the user's
  $JUJU_HOME/environments directory in order to be used. Future versions
  of Juju will make this more simple. The name of the environments file
  is the name that the user needs to use to talk to the environment, so
  the user will probably want to rename it too. For example, an
  environment named app-stack will have an env named:

  ```no-highlight
  $JUJU_HOME/environments/app-stack.jenv
  ```

  Juju will ask for a password to be typed in. If you'd prefer a strong
  random password, you can use the "--generate" option. You can also
  control the location and name of the environments file that is created.

  You can see which users have been created using the ```juju user list```
  command:

  ```bash
  juju user list
  NAME DISPLAY NAME DATE CREATED LAST CONNECTION
  admin admin 23 minutes ago just now
  test Test User 5 minutes ago never connected
  thumper Tim 5 seconds ago never connected
  ```

  The output of this command can also be in YAML or JSON using the usual
  "--format" options.

  Any user that is created will be able to access the environment. To
  stop this, you can disable the user.

  ```bash
  juju user disable test
  User "test" disabled

  juju api-info user -e local-test
  test

  juju user info -e local-test
  WARNING discarding API open error: environment "local-test" not found
  ERROR invalid entity name or password
  ```

  Unfortunately the warning there is due to legacy environment support
  that is checked as a fallback when the initial connection failed due to
  the user being disabled.

  Disabled users are not shown by default with the listing:

  ```bash
  juju user list
  NAME DISPLAY NAME DATE CREATED LAST CONNECTION
  admin admin 30 minutes ago just now
  thumper Tim 6 minutes ago never connected
  ```

  But they can be included with the '--all' option:

  ```bash
  juju user list --all
  NAME DISPLAY NAME DATE CREATED LAST CONNECTION
  admin admin 32 minutes ago just now
  test Test User 13 minutes ago 2 minutes ago (disabled)
  thumper Tim 8 minutes ago never connected
  ```

  Disabled users can be enabled again using the enable command:

  ```bash
  juju user enable test
  User "test" enabled

  juju user info -e local-test
  user-name: test
  display-name: Test User
  date-created: 14 minutes ago
  last-connection: just now
  ```
=============

**Comment by petermatulis** [comment]
**Note:** This has overlap (juju user ...) with [wip-systems](https://jujucharms.com/docs/devel/wip-systems).

**Comment by petermatulis** [comment]
Ok, I removed the overlap and linked to the multiuser-environments file.
