### ISSUE TITLE
google finds/returns outdated charmer docs 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#2682]
https://jujucharms.com/docs/stable/authors-charm-writing comes up as the first result in google. We'd prefer the newer get-started url does. 

https://jujucharms.com/docs/stable/developer-getting-started

Can we remove/move the older charm-writing and have that redirect to the developer-getting-started?

**Comment by paulgear** [comment]
This was also reported via our ticket system: when searching Google for various docs on jujucharms.com, many results point to /2.1 and /2.0 which no longer exist and toss Internal Server Error.

For example, search Google for https://www.google.com/search?q=juju+install+developer and many of the first page of results are for /2.1 and /2.0.

 * https://jujucharms.com/docs/2.0/developer-getting-started Internal Server Error
 * https://jujucharms.com/docs/2.1/reference-install Internal Server Error
 * https://jujucharms.com/docs/2.0/developer-howto Internal Server Error

**Comment by galgalesh** [comment]
We just stumbled over this too.

Please be more mindful of how docs changes affects users searching with Google since this is the primary way to use the docs for many users. At least redirect the older URLs to the newer ones so the crawler quickly realises the new url structure and you don't loose all the google-karma the pages have accumulated, and links in blog posts and on askubuntu still work..

This seems to be a systematic issue with the Juju docs:

- 1 -> 2 switch
- authors -> non-authors switch
- every new Juju version
- and now the addition of `/en/`

Obligatory [cool URIs don't change](https://www.w3.org/Provider/Style/URI)

**Comment by galgalesh** [comment]
# Example

A user wants to know how to upgrade a charm.

1. The user searches Google for for "how to upgrade juju charm" in google
2. The first two results return a 500.
3. The third result works, but that goes to the 1.x docs.
4. From the 1.x docs, the user can't go to the 2.x docs, because the "versions" sidebar acts as if this doesn't exist for versions past 1.x.
5. If the user then uses the "search" feature, they are met with [a seemingly-broken page](https://docs.ubuntu.com/search?q=upgrade&domain=docs.jujucharms.com):

- "Your search returned 0 results" even though a bunch of results are displayed.
- The header is white on grey
- The header separator flows _through_ the top search box.
- The search icon sticks to the top of the search box.
- Multiple results pointing to the same page for different versions of Juju. The only way to see that they point to the same page is to look at the url's of these results.

This does not instill confidence in the user that Juju is a stable and production-ready product. This does not meet the quality standards of Canonical imho.

**Comment by evilnick** [comment]
@galgalesh I completely agree


The solution to a great range of these issues is a bug I filed on documentation builder back in November and is the number one priority on the web-team list to solve - i.e., those search results shouldn't be the top links in google. We can mitigate the impact of that by using ever more complicated redirects, but really the solution to all this is to have the docs sites indexed properly.
If anyone wants to add any additional detail to the documentation-builder issue, it is here
https://github.com/canonical-webteam/documentation-builder/issues/96
