### ISSUE TITLE
Redirects - apart from 2.3, pages don't resolve

### ISSUE THREAD

**Issue by evilnick** [juju/docs#2738]
They shouldn't be used but apparently there are some links in existence with stuff like

jujucharms/docs/2.1/getting -started

instead of

jujucharms/docs/2.1/en/getting-started

It would be useful to map <version>/<page> to <version>/en/<page>

**Comment by evilnick** [comment]
@WillMoggridge  I'm not terribly au fait with the regex used by the redirects file - is this a simple thing you might be able to do?

**Comment by lathiat** [comment]
These URLs are heavily referenced by Google, and for whatever reason they currently index the '2.1' version for many search results. Most likely Google has determined the other versions duplicates since the content is similar.

Example: searching for "juju debug controller" returns https://docs.jujucharms.com/2.1/troubleshooting-logs

There seems to be a few things at play here
 (1) It seems we have internationalised the docs, and the old URL "https://docs.jujucharms.com/2.1/troubleshooting-logs" is still valid (with a deprecation warning) if you prefix the page with /en/, e.g. "https://docs.jujucharms.com/2.1/en/troubleshooting-logs". Redirects should be setup for the non-/en/ URLs.

 (2) This issue is made worse by the fact it just returns "Internal Server Error" for any page that is 404. We should implement a basic 404 page.

 (3) We should look at optimizing the URLs that Google Indexes, there is some ability to define Cannonical URLs and we should have some kind of non-version-specific URL for most pages. Otherwise this problem will happen frequently with new versions and generally the latest version is less likely to be shown.  More info at: https://support.google.com/webmasters/answer/139066?hl=en

**Comment by evilnick** [comment]
@lathiat thanks for the input here.

 
 1. The docs have always (since 1.12 I think) been in an /en/ directory, the historical urls were mangled by the Jujucharms site for some reason which is I guess why these persist in search

  2. Agreed. That's part of the delivery framework

  3. This is an issue with how the docs are generated, and possibly the most serious problem. https://github.com/canonical-webteam/documentation-builder/issues/96

**Comment by evilnick** [comment]
The redirects for /xxx to /en/xxx were fixed with #2771 
The  canonical link issue is already filed elsewhere
