### ISSUE TITLE
missing agent command reference

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#283]
We have the juju workstation client command reference, however it appears we are missing the agent command listing + help output as a handy reference overview. They're littered throughout the docs presently, and this means searching for new users when they just want (basically) and API listing w/ example inputs/outputs.

- config-get
- unit-get
- relation-get
- relation-set

If i'm missing any lets get them included here so when we circle back we have a complete listing.

**Comment by celebdor** [comment]
relation-list should be there as well. Basically what is on https://jujucharms.com/docs/authors-hook-environment but also showing sample json outputs.

**Comment by marcoceppi** [comment]
You can get all this data already with `juju help-tool relation-list` which
is how the other commands documentation is created (`juju help add-unit` as
an eg)

**Comment by evilnick** [comment]
@chuckbutler it isn't missing, and they aren't littered throughout the docs, they are referenced when they are relevant and included in full on the "How hooks are run" page(https://jujucharms.com/docs/authors-hook-environment). if you want to add examples there, that's fine. I will add  a link to the command reference page

**Comment by chuckbutler** [comment]
@evilnick I dont think this is very intuitive in nomenclature then in terms of users finding them in the docs. 

Whats the issue with adding them to the command reference listing under a title of "agent hookenv commands"?

**Comment by evilnick** [comment]
I will add a link, as I said, to the command reference, but I am not going to list them in full there also because:

* it may be confusing for users who expect to be able to run them with the Juju commandline
* more importantly, it is pointless to maintain the same documentation in two places.

I don't think they are hard to find if people read the documentation, and I would be concerned if people were writing hooks without reading the section "How hooks are run", but perhaps that page needs a different/better title? If people are just visiting the docs for a refresher on those items and use the search tool, that page is the first that comes up for a search on "hook tools", though sadly, the search doesn't work very well for docs so things like "config-get" return seemingly random pages. 

Personally, I think the amount of information that is being added to docs means we should actually split them into two, which may make search work better and will certainly mean we can have better navigation.

**Comment by celebdor** [comment]
@evilnick I saw the https://jujucharms.com/docs//authors-hook-environment My comment was only that there could be json output examples alongside the plaintext ones.

**Comment by evilnick** [comment]
@celebdor Thanks, and that's a good suggestion, I opened #284
