### ISSUE TITLE
update docs to reference systemd (vivid)

### ISSUE THREAD

**Issue by evilnick** [juju/docs#287]
charm authors may need to adjust for systemd under vivid

 local provider with vivid containers on non-vivid hosts has some minor issues
 juju will only work with systemd on 1.23+ (which isn't released yet, but will ship with vivid)
users will need to switch to using upstart on vivid if they want to use juju pre-1.23

**Comment by ericsnowcurrently** [comment]
Some points to consider:

* charms that directly call upstart-specific tools will need to adjust.  That includes "start", "stop", "restart", and "initctl".  We should recommend using "service" where possible.  Where it's not then the charm will need to identify the running init system and react accordingly.
* charms that install their own upstart scripts will need to adjust.  As with the upstart-specific tools, they will need to react to the currently running init system.
* It *may* make sense to add tooling to help charm authors handle different init systems.  Not only does this benefit the transition to vivid (and beyond), but also support for other platforms that use systemd (like RHEL) or other init systems (like docker).
* There's a great resource available that should help with systemd support: https://wiki.ubuntu.com/SystemdForUpstartUsers

**Comment by ericsnowcurrently** [comment]
Regarding local provider, there are two issues.

1. There is a known issue where vivid (systemd) LXC containers on
non-vivid hosts will not boot.  See
https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1347020.  This has
a direct impact on using local provider on non-vivid hosts under those
circumstances.  core is looking into a fix.  Everything works fine if local provider is
run on a vivid host.
2. There is also an issue with using lxc-create to create vivid
containers using the ubuntu-cloud template  on a non-vivid host, if
certain packages have not been updated.  See
https://bugs.launchpad.net/ubuntu/+source/cloud-utils/+bug/1062671.
This may impact some users of local provider, but probably not many.

**Comment by ericsnowcurrently** [comment]
In order to use juju 1.22 and earlier on vivid the host must be updated to boot with upstart. This can be done by running "sudo apt-get install upstart" followed by "sudo update-grub".  As well, a vivid host may be booted with upstart for a single boot.  Upon booting, in the grub menu select "Advanced options for Ubuntu" and then "Ubuntu, with Linux ... (upstart)".

We are working on updating the dist packages for earlier versions of juju to specifically require upstart.  Note that at the moment vivid is shipping with 1.20.  Once we release juju 1.23 vivid will get updated to ship with it and things should be more sane for users.

**Comment by ericsnowcurrently** [comment]
Currently when we provision new machine instances on a provider we use cloud-init to get juju all set up.  One of the steps is starting jujud via the init system, so we have to know the target init system before we provision the instance meaning we can't just check the host.  To accommodate that we decide the init system based on the juju version info.

Currently vivid (and later) map to systemd.  This will break if the instance is provisioned with an image that is booting with upstart.  To address this we've added a juju feature flag that forces the cloud-init script to use upstart instead of systemd.  To enable that, set "JUJU_DEV_FEATURE_FLAGS=legacy-upstart" in your shell environment.

**Comment by evilnick** [comment]
Thanks! i'll try and sort as much of this as I can tomorrow

**Comment by petermatulis** [comment]
Please see PR #600 for accuracy. Also put [here](http://peter.juju.papamike.ca/en/juju-systemd.html) for easy viewing.

**Comment by petermatulis** [comment]
The local provider does not bootstrap under Vivid & upstart ([LP #1450092](https://bugs.launchpad.net/juju-core/+bug/1450092)) so legacy-upstart flag is not useful.

I wonder if we should just say to not use the Local Provider on Vivid.

**Comment by evilnick** [comment]
"I wonder if we should just say to not use the local provider on Vivid."

vivid is temporal, so I am cool with that

**Comment by petermatulis** [comment]
PR #600 updated.

**Comment by petermatulis** [comment]
PR merged. Closing.
