### ISSUE TITLE
LXD instructions lead to enabling IPv6, which Juju does not support

### ISSUE THREAD

**Issue by hmlanigan** [juju/docs#2965]
The doc on using lxd with juju: https://docs.jujucharms.com/2.4/en/clouds-LXD should mention that IPv6 is not supported with juju.  During lxd init, the default behavior is to enable IPv6.

See bug:  https://bugs.launchpad.net/juju/+bug/1784018

**Comment by pmatulis** [comment]
To summarise, the workaround is to tell LXD to disable IPv6 on its bridge, usually `lxdbr0`:

`lxc network set lxdbr0 ipv6.address none`

This is unfortunate since the instructions on clouds-LXD.md use the non-interactive/ncurses method (using the interactive method is laborious to maintain at the documentation level and inefficient at the reader level). We'll have to literally include the above command until Juju supports IPv6.

**Comment by pmatulis** [comment]
What I don't understand is that these instructions worked in the past.

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LXD and IPv6](https://trello.com/c/EKGVOzZk/466-lxd-and-ipv6)

**Comment by pmatulis** [comment]
Consider #2967 at the same time.

**Comment by evilnick** [comment]
https://docs.jujucharms.com/2.4/en/tut-lxd already sets ipv6 to 'none'.

That the other page no longer works reflects changes in LXD init I believe. N.B. the tut-lxd page is also out of date in this respect (some additional options have been added)
