### ISSUE TITLE
In-page “Contents” <aside> misplaced at 100% zoom level

### ISSUE THREAD

**Issue by matthewpaulthomas** [juju/docs#3301]
Chromium 65.0, window 1191 pixels wide

1\. Go to [“Using Oracle OCI with Juju”](https://docs.jujucharms.com/2.5/en/clouds-oci).
2\. Set the zoom level to anything less _or_ more than 100%.
3\. Set the zoom level to 100%.
4\. Scroll to the bottom of the page.

What happens:

2\. A “CONTENTS” pane is visible at the right of the page.
![docs jujucharms com-layout-2](https://user-images.githubusercontent.com/19801137/51534903-ff354e80-1e3e-11e9-8a2b-6a593eb03636.png)

3\. The “CONTENTS” pane disappears.
![docs jujucharms com-layout-3](https://user-images.githubusercontent.com/19801137/51535011-415e9000-1e3f-11e9-96cd-99dc93a53588.png)

4\. The “CONTENTS” list scrolls into view, on the left, over top of the site table of contents.
![docs jujucharms com-layout-4](https://user-images.githubusercontent.com/19801137/51535027-48859e00-1e3f-11e9-8b2d-8ce96e7a699b.png)

What should happen: The contents pane stays on the right (except when this would not leave enough room for the main pane).

This may be a problem with the Discourse-docs generation in general, rather than with Juju docs in particular. However, it does not happen with “CONTENTS” lists on other Discourse-generated sites, such as [Maas “What’s new in 2.4”](https://docs.maas.io/2.4/en/intro-new) or [conjure-up “Spell walkthrough”](https://docs.conjure-up.io/stable/en/walkthrough).

**Comment by pmatulis** [comment]
Thanks for this, yet Juju documentation is not yet generated from Discourse. This problem was communicated to me for the Landscape site a few days ago (I could not locate the bug that was supposed to have been filed). Anyway, Discoursification should occur for Juju docs within the next four weeks. As for this current issue it cannot be solved by documentation. I believe you will need to put it [here](https://github.com/CanonicalLtd/jujucharms.com). As for MAAS and conjure-up, I am perplexed as I believe snapcraft is the only tech whose documentation is currently generated from Discourse.
