### ISSUE TITLE
Getting Started should cover using juju with MAAS

### ISSUE THREAD

**Issue by danboid** [juju/docs#3427]
The 'Getting Started with juju' page

https://docs.jujucharms.com/2.5/en/getting-started

Totally ignores those wanting to use juju with a MAAS server in favour of JAAS and using juju with public cloud options.When I asked about this in #maas, I was directed to:

https://docs.jujucharms.com/2.5/en/clouds-maas

So at the very minimum I think there should be a link to this page from the getting started page.

**Comment by pmatulis** [comment]
@danboid Thanks for your feedback. Juju works with many clouds though. This is explained in the opening section and includes a link to the list of supported clouds:

> The clouds that JAAS supports are: Amazon AWS, Google GCE, and Microsoft Azure. You will therefore need an account on one of these clouds in order to use JAAS. Note that Juju itself supports many more [clouds](https://docs.jujucharms.com/clouds).

Perhaps this should be called out better (e.g. "See the [full list of supported clouds](https://docs.jujucharms.com/clouds")").

**Comment by danboid** [comment]
@pmatulis 

I'm well aware juju isn't only for use with MAAS but the issue here is that with the getting started page presuming users are using JAAS or another public cloud service, a number of steps are missing to get any user with their own MAAS cloud started, such as how to creare a juju controller.

This is the only use case I'm interested in and so I felt that the getting started guide was useless to me.

**Comment by evilnick** [comment]
I think maybe a box or note calling out the other scenarios (basically MAAS, LXD and non-public OpenStack) would probably be the way to go.

The default 'getting started' can't really 'include' MAAS, because there are many differences, and to be honest, even for people who want to deploy on MAAS, using JAAS to get an idea of how Juju works is useful. The information for using MAAS is in the docs, so this is really just a signposting issue
