### ISSUE TITLE
Hard to find docs on hook tools & hook env vars

### ISSUE THREAD

**Issue by natefinch** [juju/docs#418]
It's really hard to find the docs on hook tools and environment variables that are set during hook execution.  This is perhaps the number one most valuable information a charm author can  (super important and used pretty much every time you write a charm).  They're under "how hooks are run"... which was not an obvious place for me to look.  They're important enough that I think they deserve their own page.  It would seem to be easy to split them out into their own page, and leave the "how hooks are run" info on the same page.

**Comment by evilnick** [comment]
that is essentially what that page is, so really what you are saying is it should be called something else.
Hook environment?
Hook tools and environment?

Sadly, the design limits the amount of space pages can have

**Comment by hatched** [comment]
I think the issue is that the title is "How hooks are run" instead of "Hook API" or something along those lines.

**Comment by evilnick** [comment]
Okay, I renamed the link to include Hook API. I am a little confused by this because "how hooks are run" seems quite an obvious place to look for things related to running hooks. Moreover, if you searched for 'hook environment', 'hook tools' or any number of relevant terms, it is the first result that comes up.
