### ISSUE TITLE
docs.jujucharms.com searching of release notes is poor UX

### ISSUE THREAD

**Issue by mitechie** [juju/docs#690]
Copying over from https://github.com/CanonicalLtd/jujucharms.com/issues/156 from @arosales 

If I search for a new Juju feature I heard of and it is unloaded documented in the release notes :-/ search finds it, but when I click on the text it sends me to a very long list I have to manually expand and search the page on. this is cumbersome as I have to open up each Juju release and then "Find" on the web page.

For example, I am searching for leader election.
https://jujucharms.com/docs/search/?text=leader+election&version=1.24
I click on the first returned result:
https://jujucharms.com/docs/1.24/reference-release-notes
However, now I don't see any text relating to the search results until I expand each Juju release. For leader election I had to do this until I found 1.23.2.

**Comment by mitechie** [comment]
For the record I also wonder if we can have this expanded by default vs collapsing. I'm not sure the use cases for seeing the list of releases is > the ability to find something.

**Comment by mitechie** [comment]
In thinking about this one some more, I wonder if it's be helpful to provide a direct link to the docs page in question in GH itself. In this case the link would be to https://github.com/juju/docs/blob/1.24/src/en/reference-release-notes.md

That's not the easiest to read page, but gets the user to the page and even allows them to create prs from that url

**Comment by evilnick** [comment]
Yes, there are some issues here. One is that, by default expanding all the tabs makes it *only* useful for searching. There are nearly 10000 words of text in the combined release notes, so that is one seriously large page. It may hamper people actually being able to access it properly, particularly on mobile.

One answer would be to automatically expand the section referenced - actually this would be useful for links too. Each version has an anchor, I imagine some snappy JS could determine which heading searched text was under and expand it appropriately. So maybe that would actually be in two parts - searches would resolve to a particular anchor, and some new script could auto-expand a section if it was explicitly referenced in the URL.

Pointing to the source is an option I guess, but in that case I think you would have to warn people they were leaving the docs proper.

**Comment by evilnick** [comment]
It is also worth noting that we shouldn't really be expecting people to discover things in release notes, or even rely on them for anything. The instructions for the GCE provider for example, from the same release are wrong. I can imagine searching release notes for info on when a particular thing became available though, so in some ways they are there more for historical reference rather than actual information.

**Comment by petermatulis** [comment]
It would be grand to have URLs pointing to a section foldout expanded when the page is displayed. The 'commands' page in particular is often referred to throughout the docs.

**Comment by pmatulis** [comment]
With Discoursification upon us, each release will have its own Release Notes page, linked from a central landing page. Essentially, the current collapsed headers will become links to their own page. We will end up with three Release Notes pages: 1.x, 2.x-pre-2.6, 2.x-post-2.5, with only the last one being showcased (will include links to the other two).
