### ISSUE TITLE
Search for howto-authorised-keys page is broken

### ISSUE THREAD

**Issue by tyloch** [juju/docs#699]
this page
https://jujucharms.com/docs/howto-authorised-keys/

is listed for master and other versions in search results:
https://jujucharms.com/docs/search/?text=authorized%20keys

but exists only for some e.g. 1.18:
https://jujucharms.com/docs/1.18/howto-authorised-keys

**Comment by evilnick** [comment]
Hmmm. Thanks for spotting this. It seems to be an error in search rather than the docs. The authorised keys instructions were moved as part of a new page, so you can find them here:
https://jujucharms.com/docs/stable/juju-misc#manage-access-with-authorised-ssh-keys

But you are right, search doesn't seem to find them in the correct place. @mitechie any ideas?

**Comment by mitechie** [comment]
Hmm, that whole page doesn't seem to hit the search engine. It's not found in either production or stable. The team will have to investigate this doc in particular. @urosj  @kadams54

**Comment by evilnick** [comment]
As an additional if slightly unrelated point, the search throws up matches for archived versions, which aren't currently served as far as I can tell, so often there are a few links which 404

**Comment by pmatulis** [comment]
Today, I was able to search for this information (2nd hit). Also, the search facility is being redone soon and should correct poor searching. I am closing this one.
