### ISSUE TITLE
"Report a bug on this site" points to CanonicalLtd/jujucharms.com/issues instead of here, even for documentation

### ISSUE THREAD

**Issue by basak** [juju/docs#716]
Use case:

I find a documentation issue I want to report while reading documentation.

Actual: I see "Report a bug on this site" in the footer which takes me to CanonicalLtd/jujucharms.com

Expected: AFAICT, juju/docs is the right place to submit issues against the documentation. In any case it's confusing as "Contribute to the Docs!" under "Reference" (confusingly; not sure why it's under Reference) points to juju/docs.

**Comment by evilnick** [comment]
This *is* the right place to report bugs on docs, but, confusingly, this isn't a docs bug - we don't control the page furniture on the site. I believe there is already a bug filed against this on jujucharms.

**Comment by basak** [comment]
Ah yes, sorry Nick. Clearly the other place is the right place for this
bug. I was confused!

**Comment by petermatulis** [comment]
@evilnick 
I could only find [#191](https://github.com/CanonicalLtd/jujucharms.com/issues/191) on jujucharms and it is strictly about the appearance and placement of the 'report bug' link and not its target, which is the nature of this current issue. From your comment it's unclear whether you consider the current target inappropriate. I certainly do. Yet if it's a footer across many sites then a change would be problematic. We may be better off changing the link appearance to something more descriptive ("Report a bug on the structure of this site.").

In terms of submitting content bugs, the current instructions are very weak. The [contributing](https://jujucharms.com/docs/stable/contributing) page only has

> Fork the repository from github.com/juju/docs

That page should include explicit instructions for bug reporting but there is also the need for a prominent link. I propose a standalone link at the very bottom of the menu in the left pane.

Comments?

**Comment by evilnick** [comment]
I don't think people should have to hunt down things in 'Contribute!' to report problems, I think there should be a link at the bottom of the page which says "report an issue" or whatever. That should point to the juju/docs issues page; quite simple.

I don't really care if this is a special extra link for docs, or the same link that directs to docs issues when it is followed from a docs page (we do get issues filed on jujucharms about docs which people are kind enough to copy over). there is an outstanding issue about this, but i couldn't tell you exactly where it is or even which of the projects it is filed against because I reported it over a year ago (along with a heap of other things like the wrong styles, wrong handling of graphics, etc etc).

**Comment by petermatulis** [comment]
The essential problem of people not being able to find a link to report a docs issue has been resolved via PR #876 (link in contribute page and link at bottom of left pane). The [jujucharms issue #191](https://github.com/CanonicalLtd/jujucharms.com/issues/191) remains open and I commented how to deal with it. I'm closing this present issue.
