### ISSUE TITLE
Hook tools should be listed in the reference section

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#722]
Charm Authors would benefit from a list of what commands are available to them in a hookenvironment. Such as:

is-leader, status-set, config-get et-al, in an index/appendix format.

Similar to: https://jujucharms.com/docs/stable/authors-hook-environment  

maybe we should split this apart into its own listing, and cross reference when applicable?

**Comment by kat-co** [comment]
+1 I couldn't find it.

**Comment by kat-co** [comment]
Also, can we make it a little easier to digest? e.g.:

| Name | 1.20 | 1.21 | 1.22 | 1.23 | 1.24 | 1.25 |
|---|---|---|---|---|---|---|
| [status-set](#) | red | red | red | red | green | green |

**Comment by evilnick** [comment]
The list of hook-tools is included in https://jujucharms.com/docs/devel/authors-hook-environment
(does not currently include tools from experimental features)

I don't think that is the most 'findable' place for it, and the name of the page has been the subject of some debate previously, when it was changed to placate other core devs.

I think it merits putting the list in the reference section, because nobody ever seems to be able to find them, even though it is the first hit for a search on 'hook tools' (maybe people aren't aware that's what we call them).

**Comment by kat-co** [comment]
Yes, the reference section is where I would have expected it.
