### ISSUE TITLE
Developer guide cites OS-specific instructions

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#767]
There are probably other places that this happens, but one example of it is in `developer-getting-started.md`. Under the Charm Tools section, a bash example cites using apt-get to install charm-tools. This example is invalid for developers using OS X or Windows.

Rather, we should use platform-agnostic language to tell the developer how to use tools for their platform. In this case, charm-tools is available as `charm-tools` for Ubuntu-based systems, as `charm-tools` for OS X systems with brew installed, however it's packaged for Windows, and finally as `charm-tools-blah.tar.gz` downloaded from Launchpad and/or Github for everyone else.

Again, this isn't the only place we're using platform-specific instruction so those should also be identified and fixed, especially as we add support for more platforms.

**Comment by mbruzek** [comment]
In a meeting with Weave today we saw these papercuts with OSX and brew. We should have OSX steps/commands in our docs as well. Our Weave partners could not run `charm build` because he didn't have everything installed and it was not obvious with the error messages he saw what to do next.

[ ] Need to add install "charm-tools" instructions:  `brew install charm-tools`
[ ] Need to add install python3 instructions: `brew install python3`

We still encountered an error running `charm build` after these commands, it looked to me like the error message still had python 2.7 in the path.

**Comment by AdamIsrael** [comment]
The developer getting started guide has been rewritten since I opened this bug, and the new documentation for installing juju and its related tools now covers OS-specific instruction details.
