### ISSUE TITLE
troubleshooting page is broken

### ISSUE THREAD

**Issue by evilnick** [juju/docs#833]
https://jujucharms.com/docs/stable/troubleshooting

broken links, very little text, etc.

**Comment by evilnick** [comment]
thanks @fabricematrat for pointing this out

**Comment by evilnick** [comment]
from #842 :

The link to juju troubleshooting says "coming soon"
https://jujucharms.com/docs/devel/troubleshooting

I'd suggest as an interim we use this post from @castrojo 's blog

http://www.jorgecastro.org/2014/05/29/real-world-juju-troubleshooting/

**Comment by ns950** [comment]
(newbie here).  How long does it take for -devel to propage to -stable? I see diffs between them currently. 

I was going to suggest that in the interim, rather than having a broken link to nowhere, just have text instead. I have patched this in [my fork](https://github.com/ns950/docs/tree/tshoot-833), should this be worth a pull request. Is there a system-wide policy about these kind of situations? I personally as a reader vastly prefer text links rather than having to wait on a web timeout unnecessarily. --Nivedita

**Comment by marcoceppi** [comment]
@ns950 so devel is the devel version of Juju and stable is target at the current version of Juju. It's not meant to be the version of the doc. That said, as soon as Juju 2.0 (next stable) is released devel will become stable.

Since we don't have a page yet, fixing the link until it's available might be a good approach, but I'll leave that to @evilnick

**Comment by ns950** [comment]
Thanks for the clarification.
