### ISSUE TITLE
lxd-images is deprecated

### ISSUE THREAD

**Issue by mitechie** [juju/docs#934]
The documentation on https://jujucharms.com/docs/devel/config-LXD uses lxd-images which is deprecated. See https://github.com/lxc/lxd/issues/1036 and https://github.com/lxc/lxd/issues/1462 .

copied for @nskaggs from https://github.com/CanonicalLtd/jujucharms.com/issues/233

**Comment by pmatulis** [comment]
Yes, we know. The Ubuntu images were updated very recently.

The problem is that removing lxd-images (from the page), which still resides on plenty of Xenial installations, will make the documentation even worse because Juju does not create the image alias automatically yet, at least for Xenial. When is *that* going to happen?

**Comment by cherylj** [comment]
> Juju does not create the image alias automatically yet, at least for Xenial. When is that going to happen?

Beta3.  It's already in master.
