### ISSUE TITLE
https://juju.ubuntu.com/docs/howto-node.html needs to match latest charm config.

### ISSUE THREAD

**Issue by didrocks** [juju/docs#94]
https://juju.ubuntu.com/docs/howto-node.html is pointing at using juju deploy --config myapp.yaml node-app myapp.
However myapp.yaml is wrong, there is no repo options, it seems to be app_url instead.
Also, the config example should reflect the name of the charm.

More IRC context:
 didrocks | I have a small question, on jcastro's advice, I'm following https://juju.ubuntu.com/docs/howto-node.html  
 didrocks | I was wondering about the node-app charm to set the right repo  
 didrocks | it's pointing at juju deploy --config myapp.yaml node-app myapp  
 didrocks | with the yaml being:  
 didrocks | sample-node:  
 didrocks |   repo: https://github.com/yourapplication  
 didrocks | however, in the charm itself (http://manage.jujucharms.com/charms/precise/node-app), I see that the config is using app_url  
 didrocks | I'm probably missing one transformation step :)  
lazyPower | didrocks: you discovered a bug in the docs, good catch.  
lazyPower | didrocks: would you mind filing a bug? https://github.com/juju/docs  
 didrocks | lazyPower: ah nice, can do, for sure, so the name should be mapping the charm config?  
     jose | didrocks, lazyPower: I can fix it right now  
 didrocks | jose: still want the bug opened?  
     jose | ask lazyPower!  
lazyPower | didrocks: when you say name should be mapping the charm config, what do you mean?  
 didrocks | lazyPower: options in the yaml config like "repo" should be the one in the charm config options  
  jcastro | the config is missing on the charm page  
  jcastro | I think the docs are referring to a config option that either doesn't exist, or used to exist and bitrotted  
lazyPower | well, looking at the docs, this is really confusing, a) there is no repo config options, its app_url  
 didrocks | yeah, seems to be app_url  
lazyPower | and the name at the top of that config example should reflect the name of the charm  
lazyPower | eg, if you deploy node-app charm as "hoobadooba", it should read: hoobadooba: app_url: http://myawesomegithub.git  
 didrocks | oh, so not "sample-node" but "node-app"?  
lazyPower | right  
 didrocks | ah ok :)

**Comment by mblanken** [comment]
In the line "juju deploy --config myapp.yaml node-app myapp" this final word "myapp" then becomes the key lookup in the myapp.yaml file and also needs to be in the app_name entry.  So the documentation is wrong since it includes "node-app" as the key for the example config file.  The documentation should consistently refer to the github location as ending in .git to avoid confusion.

    myapp:
      app_name: myapp
      app_url: http://github.com/mmm/myapp.git

Additionally, it looks like the only version of node-app in the charms library is for Precise and I'd guess that everybody's on Trusty now.  Attempting this combination will result in a failed deployment since there are no Precise nodes to land on.

**Comment by marcoceppi** [comment]
Thanks for the catch regarding naming mismatch! I'll submit an update to the docs shortly to address this.

As for precise, there shouldn't be a problem deploying the precise charm as we still publish precise images and it's still under support by Canonical. While I agree most people are on trusty now, deploying a mixed bag of trusty services and precise services shouldn't be an issue.

**Comment by mblanken** [comment]
Thanks.

My entire rig is Trusty and so when I first attempted to just "juju deploy node-app myapp" it ultimately failed since the default appears to be Precise.  (This is a bit lost on relatively-noobish users such as myself, weighing in at only 8 weeks of experience with this yet.)  It was quite the learning curve to figure out how to find and deploy a Trusty version of this out there in userspace.  Attempting to translate the new command "juju deploy --config myapp.yaml cs:~someone/node-app-10 myapp" kept failing similarly as it tries to bind a key in the config file.  Given the aforementioned documentation problem that left me wondering--for a while at least--how exactly all this worked.
