### ISSUE TITLE
Missing release notes for devel section?

### ISSUE THREAD

**Issue by mitechie** [juju/docs#976]
I tried to find the release notes for Juju 2.0 beta and couldn't. After asking around, I was given the link to a Google Doc.

Copied for @sparkiegeek from https://github.com/CanonicalLtd/jujucharms.com/issues/244

**Comment by evilnick** [comment]
This raises a couple of issues.

1. historically, we have never published release notes for devel versions in the documentation, mainly because they are by nature ephemeral. Do we really want to start including those as a matter of course?

2. Currently the devel version is a work in progress towards the next stable version of docs. 2.0 is a special case in many ways, but it is still a work in progress. The devel version of docs is *NOT* currently a finished version of docs for the dev versions of Juju and never really can be, though you may find useful information there.

P.S. as a convenience for people trying the alpha/beta versions, we did actually include release notes on a special page. You can find them linked from the [introducing Juju 2 page](https://jujucharms.com/docs/devel/introducing-2)
